# -*- coding: utf-8 -*-
"""AI_SQL.ipynb

Automatically generated by Colab.

"""

!pip install openai

import sqlite3
import os
from openai import OpenAI


# 1.API Key
os.environ["OPENAI_API_KEY"] = "YOUR_API_KEY_HERE"
client = OpenAI()


# 2.init_db
def init_db():
    conn = sqlite3.connect('expense_tracker.db')
    cursor = conn.cursor()

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS expenses (
        id INTEGER PRIMARY KEY,
        amount REAL,
        date_incurred TEXT,
        category TEXT,
        method TEXT
    )
    ''')

    cursor.execute('SELECT count(*) FROM expenses')
    if cursor.fetchone()[0] == 0:
        data = [
            (15.50, '2025-10-01', 'Food', 'Credit Card'),
            (45.00, '2025-10-02', 'Transport', 'Debit Card'),
            (120.00, '2025-10-05', 'Entertainment', 'Cash'),
            (1200.00, '2025-10-01', 'Rent', 'Bank Transfer')
        ]
        cursor.executemany('INSERT INTO expenses (amount, date_incurred, category, method) VALUES (?, ?, ?, ?)', data)
        conn.commit()
        print("Database created")
    else:
        print("Database is ready")
    conn.close()

def ask_gpt(question):
    # Schema Linking
    schema = "Table: expenses (Columns: id, amount, date_incurred, category, method)"
    prompt = f"{schema}\nUser Question: {question}\nWrite a SQLite SQL query. Return ONLY SQL."

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content.replace("```sql", "").replace("```", "").strip()

def run_query(sql):
    conn = sqlite3.connect('expense_tracker.db')
    try:
        cursor = conn.cursor()
        cursor.execute(sql)
        result = cursor.fetchall()
        return result
    except Exception as e:
        return f"SQL Error: {e}"
    finally:
        conn.close()

def natural_language_answer(question, result):
    prompt = f"User: {question}\nDB Result: {result}\nAnswer in a friendly sentence."
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

init_db()

specific_question = "Who is the manager of the store I went to?"

print(f"\n Questions: {specific_question}")
sql = ask_gpt(specific_question)
print(f"SQL: {sql}")

result = run_query(sql)
print(f"Result: {result}")

final_answer = natural_language_answer(specific_question, result)
print(f"AI_Response: {final_answer}")